# @package dataset
defaults:
  - /dataset/default  # conf/dataset/default.yaml

_target_: winlp.task.token_classification.TokenClassificationDataModule
label_all_tokens: ${task.label_all_tokens}
label_column_name: ner_tags