defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

datamodule:
  _target_: winlp.task.text_classification.data.TextClassificationDataModule
  dataset_name: "datasets/text_classification/imdb_sentiment_classification"
  pretrained_model_name_or_path: "distilbert-base-uncased"
  max_length: 128
  batch_size: 32

module:
  _target_: winlp.task.text_classification.model.TextClassificationModule
  pretrained_model_name_or_path: "distilbert-base-uncased"
  num_labels: 2
  monitor: "val_loss"
  mode: min
  learning_rate: 2e-5

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  deterministic: True
  max_epochs: 5
  logger:
    _target_: lightning.pytorch.loggers.MLFlowLogger
    experiment_name: "Text-Classification-IMDb"
    run_name: "distilbert-base-uncased-1"
    tracking_uri: "./test/mlflow"
    log_model: False