# @package dataset
defaults:
  - /dataset/default  # conf/dataset/default.yaml

_target_: haonlp.task.token_classification.boundary_detection.BoundaryDetectionDataModule
dataset_name:
  - /home/bryant/HaoNLP/datasets_hub/boundary_detection/chest_ct_tokenize/program_data/chest_ct_tokenize_2024-01-23-07-41
label_column_name: Tags
indices_column_name: Indices
label_list:
  - O
  - Token